version: '3.8'

services:
  zhenzhen-pro:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # 可以在这里配置环境变量
      - BASE_URL=${BASE_URL:-http://172.28.1.17:3009/v1}
      - API_KEY=${API_KEY:-sk-fLo3J9UUg2mgx54wxlQbnOluoxe4DQxqHTTHcqB2WL2fsK4h}
      - PROXY_URL=${PROXY_URL:-https://ai-zhenzhen.yunzuoye.net}
    volumes:
      # 挂载assets目录（如果需要持久化）
      - ./assets:/app/assets:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:8000/', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - zhenzhen-pro
    restart: unless-stopped
    profiles:
      - with-proxy
